// Query
export const QUERY = 'QUERY';
export const GET_QUERY = 'GET_QUERY';

export const ADD_ROW = 'ADD_ROW';
export const REMOVE_ROW = 'REMOVE_ROW';
export const CHANGE_ROW_FIELD = 'CHANGE_ROW_FIELD';
export const CHANGE_ROW_PACKAGE_NAME = 'CHANGE_ROW_PACKAGE_NAME';
export const CHANGE_ROW_USER = 'CHANGE_ROW_USER';
export const CHANGE_ROW_PACKAGE_TYPE = 'CHANGE_ROW_PACKAGE_TYPE';
export const CHANGE_ROW_UPLOAD_STATUS = 'CHANGE_ROW_UPLOAD_STATUS';
export const CHANGE_ROW_PACKAGE_SIZE = 'CHANGE_ROW_PACKAGE_SIZE';
export const CHANGE_ROW_DATE = 'CHANGE_ROW_DATE';

export const ADD_GROUP = 'ADD_GROUP';
export const REMOVE_GROUP = 'REMOVE_GROUP';
export const UPDATE_FIELDS_IN_GROUP = 'UPDATE_FIELDS_IN_GROUP';
